wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1676921374.279433
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.9.5
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: GCN
epochs:
  desc: null
  value: 180
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: f1_loss
optimizer:
  desc: null
  value: Adam
out_channels:
  desc: null
  value: 64
