wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1676808280.494572
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.10
      8:
      - 1
      - 5
architecture:
  desc: null
  value: GCN
epochs:
  desc: null
  value: 180
hidden_channels:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 1.0e-06
loss:
  desc: null
  value: f1_loss
optimizer:
  desc: null
  value: Adam
out_channels:
  desc: null
  value: 64
